apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector: #selector utilizado na criação do service
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2-alpine
        resources:
          limits:
            memory: 128Mi
            cpu: 200m
          requests:
            cpu: 200m
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-index
          readOnly: true

      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index
          items:
          - key: index.html
            path: nginx-index